- name: Setup Redis and Frontend Servers
  hosts:
    - server_role_redis_server
    - server_role_frontend_server
  roles:
    - frontend
    - redis
  become: true
  gather_facts: true # Collect facts only once for the entire play

  vars:
    # Set remote_user conditionally for each server role
    ansible_user: "{{ 'rocky' if 'server_role_redis_server' in group_names else 'ubuntu' }}"
  
    
    
   
  
    
